name: mocki
port: 3000
endpoints:

  - path: /hello
    method: get
    responses:
      - statusCode: 200
        body:
          message: Hello from Mocki!


  - path: /hello2
    method: get
    responses:
      - statusCode: 200
        body:
          message: Hello from 2Mocki!