name: mocki
port: 3000
endpoints:

  - path: /hello
    method: get
    responses:
      - statusCode: 200
        headers:
          - name: content-type
            value: application/json
        body: |
          {"message": "Hello from 2Mocki!"}

